# The URL the site will be built for
base_url = "https://klimacamp-halle.org"

default_language = "de"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme ="zola-bearblog"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
date_format="%d %b, %Y"

hide_made_with_line = true

[[extra.main_menu]]
name = "Programm"
url = "@/programm.md"

[[extra.main_menu]]
name = "Wir über uns"
url = "@/wir.md"

[[extra.main_menu]]
name = "Anfahrt"
url = "@/anfahrt.md"

[[extra.main_menu]]
name = "Kontakt"
url = "@/kontakt.md"



