# The URL the site will be built for
base_url = "https://klimacmap-halle.org"

default_language = "de"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme ="sam"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

sam_menu = [
    { text = "Programm", link = "/programm" },
    { text = "Anfahrt", link = "/anfahrt" },
    { text = "Kontakt", link = "/kontakt" },
]

#hackish way to add another menu for english site
sam_menu_en = [
    { text = "Program", link = "/en/programm" },
    { text = "Journey", link = "/en/anfahrt" },
    { text = "Contact", link = "/en/kontakt" },
]

# Disable menu at the bottom
sam_bottom_menu = false

# Disable word count and reading time
show_word_count = false
show_reading_time = false

[languages.en]
[languages.pl]
